# Site settings
title: greglgomez
email: greglgomez@pm.me
baseurl: ""
url: ""
twitter_username: greglgomez
github_username:  greglgomez

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Content collections
collections_dir: collections
collections:
  posts:
    output: true
  projects:
    output: true

# Layout overrides
defaults:
  - scope:
      path: "/wiki/*"
    values:
      layout: "wiki"